### ISSUE TITLE
Getting errors when trying example html

### ISSUE THREAD

**Issue by tobiasger** [dxu/matter-collision-events#1]
Forgive me if I'm just being a noob right now, but I downloaded your master branch, did `npm install` in the directory and did the `python -m SimpleHTTPServer 3000` command. When I visit http://localhost:3000 I get the following errors:

<img width="574" alt="skarmavbild 2017-04-30 kl 18 04 12" src="https://cloud.githubusercontent.com/assets/18483324/25565843/81c2734e-2dcf-11e7-88ef-7ac9e6afaed3.png">

**Comment by dxu** [comment]
hey tobias, thanks for reporting this, I incorrectly defined the `externals` config in webpack. I've fixed it and released a patch, so if you update to `v0.1.6` you should be able to correctly view the example code. If you're using the git repo directly, you should be able to just pull to get the new updates.

Closing this, but feel free to reopen or file a new issue if you continue running into problems.
